DELETE USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'TRAMSTOP'
AND COLUMN_NAME = 'STUDENTPOSITION';

drop table TRAMSTOP;

DELETE USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'BUILDING'
AND COLUMN_NAME = 'SHAPE';

DROP TABLE BUILDING;

DELETE USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = 'STUDENTS'
AND COLUMN_NAME = 'STUDENTPOS';

DROP TABLE STUDENTS;
